In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [6]:
games = pd.read_csv('resources/nfl_data_with_final_win_percentages.csv')
games.head()

C:\Users\setho\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (79) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Game ID,schedule_date,schedule_season,schedule_week,schedule_week_clean,schedule_playoff,team,team_id,cumulative_win_percent,...,temp_32_to_80,temp_above_80,weather_wind_mph,wind_below_15,wind_GTE_15,win_lose_draw,stadium,stadium_surface,weather_humidity,weather_detail
0,0,5,9/11/1966,1966,1,1,False,Atlanta Falcons,ATL,0.5,...,1,0,7.0,1,0,1,Atlanta-Fulton County Stadium,0,57,NaN
1,1,19,9/18/1966,1966,2,2,False,Atlanta Falcons,ATL,1.0,...,1,0,5.0,1,0,1,Franklin Field,"Grass, Turf (1969-1970)",74,NaN
2,2,29,9/25/1966,1966,3,3,False,Atlanta Falcons,ATL,1.0,...,1,0,9.0,1,0,1,Tiger Stadium,Grass,58,NaN
3,3,38,10/2/1966,1966,4,4,False,Atlanta Falcons,ATL,1.0,...,1,0,12.0,1,0,1,Atlanta-Fulton County Stadium,0,63,NaN
4,4,54,10/9/1966,1966,5,5,False,Atlanta Falcons,ATL,1.0,...,1,0,4.0,1,0,1,RFK Memorial Stadium,0,77,NaN

In [15]:
#games.drop("stadium_neutral", axis=1, inplace=True)
games = games.dropna(inplace=True)
games_d = games.astype(float)
games_clean.head()

SyntaxError: invalid syntax (<ipython-input-15-272355c39803>, line 3)

In [8]:
X = games.drop("win_lose_draw", axis=1)
y = games["win_lose_draw"].values.reshape(-1, 1)
print(X.shape, y.shape)

(196, 80) (196, 1)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [10]:
# Create a logistic regression model

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [11]:
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'Rain'

In [14]:
classifier.score(X_train, y_train)
print(f'Clf score on train data is {classifier.score(X_train, y_train)}')
print(f'Clf score on test data is {classifier.score(X_test, y_test)}')

Clf score on train data is 0.6568762009332967
Clf score on test data is 0.6669411280362288

In [15]:
predictions = classifier.predict(X_test)

In [16]:
accuracy = pd.DataFrame({"Prediction": list(predictions), "Actual": y_test.ravel()}).reset_index(drop=True)
accuracy['correct'] = accuracy.Prediction == accuracy.Actual
accuracy.head(15)

    Prediction  Actual  correct
0            0       0     True
1            1       1     True
2            0       0     True
3            0       0     True
4            0       1    False
5            1       1     True
6            0       1    False
7            0       0     True
8            1       0    False
9            1       0    False
10           1       0    False
11           1       1     True
12           0       0     True
13           1       1     True
14           1       0    False

###__---------------------------------------------_________--

In [18]:
games_with_win_perc = pd.read_csv('nfl_data_with_final_win_percentages.csv')
games_with_win_perc.head()

,cum_win_25,cum_win_50,cum_win_75,cum_win_100,Miami Dolphins,Oakland Raiders,Houston Oilers,Denver Broncos,San Diego Chargers,Buffalo Bills,...,stadium_outdoors,stadium_retractable,stadium_neutral_true,stadium_neutral_false,temp_below_32,temp_32_to_80,temp_above_80,wind_below_15,wind_GTE_15,win_lose_draw
0,0,0,1,0,0,0,0,0,0,0,...,0.0,0.0,0,1,0,1,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,0,1,1
3,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0,1,0,1,0,1,0,1
4,0,0,1,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,1,0,1

In [19]:
games_with_win_perc.dropna(inplace=True)
games_with_win_perc.head()

,cum_win_25,cum_win_50,cum_win_75,cum_win_100,Miami Dolphins,Oakland Raiders,Houston Oilers,Denver Broncos,San Diego Chargers,Buffalo Bills,...,stadium_outdoors,stadium_retractable,stadium_neutral_true,stadium_neutral_false,temp_below_32,temp_32_to_80,temp_above_80,wind_below_15,wind_GTE_15,win_lose_draw
0,0,0,1,0,0,0,0,0,0,0,...,0.0,0.0,0,1,0,1,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,0,1,1
3,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0,1,0,1,0,1,0,1
4,0,0,1,0,0,0,0,0,0,0,...,1.0,0.0,0,1,0,1,0,1,0,1

In [20]:
X2 = games.drop("win_lose_draw", axis=1)
y2 = games["win_lose_draw"].values.reshape(-1, 1)
print(X2.shape, y2.shape)

(19430, 56) (19430, 1)

In [21]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=1, stratify=y)

In [22]:
classifier2 = LogisticRegression()
classifier2

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [24]:
classifier2.fit(X2_train, y2_train)

C:\Users\Tai\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Tai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Tai\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
classifier2.score(X2_train, y2_train)
print(f'Clf score on train data is {classifier2.score(X2_train, y2_train)}')
print(f'Clf score on test data is {classifier2.score(X2_test, y2_test)}')

Clf score on train data is 0.6568762009332967
Clf score on test data is 0.6669411280362288