In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# load dataset
# Read the csv file into a pandas DataFrame

nfl_df = pd.read_csv("resources/nfl_data_with_final_win_percentages.csv")
list(nfl_df)
# nfl_df.head()

C:\Users\setho\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (79) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

['Unnamed: 0',
 'Game ID',
 'schedule_date',
 'schedule_season',
 'schedule_week',
 'schedule_week_clean',
 'schedule_playoff',
 'team',
 'team_id',
 'cumulative_win_percent',
 'cum_win_25',
 'cum_win_50',
 'cum_win_75',
 'cum_win_100',
 'Miami Dolphins',
 'Oakland Raiders',
 'Houston Oilers',
 'Denver Broncos',
 'San Diego Chargers',
 'Buffalo Bills',
 'Green Bay Packers',
 'Baltimore Colts',
 'Atlanta Falcons',
 'Los Angeles Rams',
 'Detroit Lions',
 'Chicago Bears',
 'Pittsburgh Steelers',
 'New York Giants',
 'San Francisco 49ers',
 'Minnesota Vikings',
 'St. Louis Cardinals',
 'Philadelphia Eagles',
 'Washington Redskins',
 'Cleveland Browns',
 'New York Jets',
 'New England Patriots',
 'Kansas City Chiefs',
 'Dallas Cowboys',
 'Boston Patriots',
 'New Orleans Saints',
 'Cincinnati Bengals',
 'Tampa Bay Buccaneers',
 'Seattle Seahawks',
 'Los Angeles Raiders',
 'Indianapolis Colts',
 'Phoenix Cardinals',
 'Arizona Cardinals',
 'Carolina Panthers',
 'St. Louis Rams',
 'Jacksonville Jaguars',
 'Baltimore Ravens',
 'Tennessee Oilers',
 'Tennessee Titans',
 'Houston Texans',
 'Los Angeles Chargers',
 'Home',
 'Away',
 'team_favorite_id',
 'Favorite_to_Win',
 'Favorite_to_Lose',
 'spread_favorite',
 'spread_favorite_clean',
 'stadium_indoors_outdoors',
 'stadium_indoors',
 'stadium_outdoors',
 'stadium_retractable',
 'stadium_neutral',
 'stadium_neutral_true',
 'stadium_neutral_false',
 'weather_temperature',
 'temp_below_32',
 'temp_32_to_80',
 'temp_above_80',
 'weather_wind_mph',
 'wind_below_15',
 'wind_GTE_15',
 'win_lose_draw',
 'stadium',
 'stadium_surface',
 'weather_humidity',
 'weather_detail']

In [3]:
#clean dataframe

nfl_df = nfl_df.drop(columns=['Unnamed: 0','team','team_id','team_favorite_id','stadium_indoors_outdoors','weather_temperature',
                              'stadium','stadium_surface','stadium_indoors_outdoors','weather_humidity',
                              'stadium_neutral','weather_detail','weather_wind_mph','stadium_neutral','schedule_date',
                              'schedule_season','schedule_week'])
# Drop the null columns where all values are null
nfl_df = nfl_df.dropna(axis='columns', how='all')
# Drop the null rows
nfl_df = nfl_df.dropna()
nfl_df.head()

,Game ID,schedule_week_clean,schedule_playoff,cumulative_win_percent,cum_win_25,cum_win_50,cum_win_75,cum_win_100,Miami Dolphins,Oakland Raiders,...,stadium_outdoors,stadium_retractable,stadium_neutral_true,stadium_neutral_false,temp_below_32,temp_32_to_80,temp_above_80,wind_below_15,wind_GTE_15,win_lose_draw
136,171,17,True,0.133333,1,0,0,0,0,0,...,1.0,0.0,1,0,0,1,0,1,0,0
166,171,18,True,0.133333,1,0,0,0,0,0,...,1.0,0.0,1,0,0,1,0,1,0,1
479,351,17,True,0.250000,0,1,0,0,0,0,...,1.0,0.0,1,0,0,1,0,1,0,0
617,351,19,True,0.066667,1,0,0,0,0,1,...,1.0,0.0,1,0,0,1,0,1,0,1
732,539,17,True,0.062500,1,0,0,0,0,0,...,1.0,0.0,1,0,0,1,0,1,0,1

In [4]:
#create train test split
from sklearn.model_selection import train_test_split

y = nfl_df['win_lose_draw']
X = nfl_df.drop(columns=['win_lose_draw'])

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [5]:
X_train.head()

,Game ID,schedule_week_clean,schedule_playoff,cumulative_win_percent,cum_win_25,cum_win_50,cum_win_75,cum_win_100,Miami Dolphins,Oakland Raiders,...,stadium_indoors,stadium_outdoors,stadium_retractable,stadium_neutral_true,stadium_neutral_false,temp_below_32,temp_32_to_80,temp_above_80,wind_below_15,wind_GTE_15
16403,8275,10,False,0.625000,0,0,1,0,0,0,...,0.0,1.0,0.0,0,1,0,1,0,1,0
15973,7882,1,False,0.500000,0,0,1,0,0,0,...,0.0,1.0,0.0,0,1,0,0,1,1,0
11781,5901,4,False,1.000000,0,0,0,1,0,0,...,1.0,0.0,0.0,0,1,0,1,0,1,0
11626,5814,16,False,0.384615,0,1,0,0,0,0,...,0.0,1.0,0.0,0,1,0,1,0,1,0
5953,3010,4,False,0.666667,0,0,1,0,0,0,...,0.0,1.0,0.0,0,1,0,1,0,1,0

In [6]:
#pre-processing
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

X_scaler = MinMaxScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

In [8]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [9]:
 y_train_categorical.shape

(14605, 3)

In [10]:
#create and train deep learning model using keras

model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=65))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

WARNING:tensorflow:From C:\Users\setho\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [11]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               6600
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303
=================================================================
Total params: 17,003
Trainable params: 17,003
Non-trainable params: 0
_________________________________________________________________

In [13]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\setho\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/60
 - 1s - loss: 0.6630 - acc: 0.6520
Epoch 2/60
 - 1s - loss: 0.6457 - acc: 0.6586
Epoch 3/60
 - 1s - loss: 0.6391 - acc: 0.6593
Epoch 4/60
 - 1s - loss: 0.6361 - acc: 0.6568
Epoch 5/60
 - 1s - loss: 0.6327 - acc: 0.6592
Epoch 6/60
 - 1s - loss: 0.6265 - acc: 0.6616
Epoch 7/60
 - 1s - loss: 0.6237 - acc: 0.6618
Epoch 8/60
 - 1s - loss: 0.6211 - acc: 0.6650
Epoch 9/60
 - 1s - loss: 0.6174 - acc: 0.6668
Epoch 10/60
 - 1s - loss: 0.6128 - acc: 0.6708
Epoch 11/60
 - 1s - loss: 0.6114 - acc: 0.6713
Epoch 12/60
 - 1s - loss: 0.6077 - acc: 0.6765
Epoch 13/60
 - 1s - loss: 0.6027 - acc: 0.6790
Epoch 14/60
 - 1s - loss: 0.6002 - acc: 0.6831
Epoch 15/60
 - 1s - loss: 0.5977 - acc: 0.6823
Epoch 16/60
 - 1s - loss: 0.5947 - acc: 0.6866
Epoch 17/60
 - 1s - loss: 0.5925 - acc: 0.6881
Epoch 18/60
 - 1s - loss: 0.5883 - acc: 0.6900
Epoch 19/60
 - 1s - loss: 0.5858 - acc: 0.6916
Epoch 20/60
 - 1s - loss: 0.5834 - acc: 0.6942
Epoch 21/60
 - 1s - loss: 0.5798 - acc: 0.6977
Epoch 22/60
 - 1s - loss: 0.5769 - acc: 0.6954
Epoch 23/60
 - 1s - loss: 0.5735 - acc: 0.7006
Epoch 24/60
 - 1s - loss: 0.5716 - acc: 0.7009
Epoch 25/60
 - 1s - loss: 0.5677 - acc: 0.7050
Epoch 26/60
 - 1s - loss: 0.5650 - acc: 0.7059
Epoch 27/60
 - 1s - loss: 0.5608 - acc: 0.7091
Epoch 28/60
 - 1s - loss: 0.5611 - acc: 0.7094
Epoch 29/60
 - 1s - loss: 0.5559 - acc: 0.7094
Epoch 30/60
 - 1s - loss: 0.5527 - acc: 0.7111
Epoch 31/60
 - 1s - loss: 0.5512 - acc: 0.7143
Epoch 32/60
 - 1s - loss: 0.5492 - acc: 0.7147
Epoch 33/60
 - 1s - loss: 0.5464 - acc: 0.7130
Epoch 34/60
 - 1s - loss: 0.5408 - acc: 0.7209
Epoch 35/60
 - 1s - loss: 0.5392 - acc: 0.7214
Epoch 36/60
 - 1s - loss: 0.5348 - acc: 0.7250
Epoch 37/60
 - 1s - loss: 0.5337 - acc: 0.7274
Epoch 38/60
 - 1s - loss: 0.5314 - acc: 0.7279
Epoch 39/60
 - 1s - loss: 0.5275 - acc: 0.7272
Epoch 40/60
 - 1s - loss: 0.5268 - acc: 0.7293
Epoch 41/60
 - 1s - loss: 0.5233 - acc: 0.7316
Epoch 42/60
 - 1s - loss: 0.5194 - acc: 0.7318
Epoch 43/60
 - 1s - loss: 0.5179 - acc: 0.7353
Epoch 44/60
 - 1s - loss: 0.5169 - acc: 0.7354
Epoch 45/60
 - 1s - loss: 0.5116 - acc: 0.7382
Epoch 46/60
 - 1s - loss: 0.5106 - acc: 0.7397
Epoch 47/60
 - 1s - loss: 0.5073 - acc: 0.7415
Epoch 48/60
 - 1s - loss: 0.5042 - acc: 0.7393
Epoch 49/60
 - 2s - loss: 0.5017 - acc: 0.7455
Epoch 50/60
 - 1s - loss: 0.4985 - acc: 0.7431
Epoch 51/60
 - 1s - loss: 0.4990 - acc: 0.7431
Epoch 52/60
 - 1s - loss: 0.4961 - acc: 0.7481
Epoch 53/60
 - 1s - loss: 0.4931 - acc: 0.7493
Epoch 54/60
 - 1s - loss: 0.4900 - acc: 0.7489
Epoch 55/60
 - 1s - loss: 0.4876 - acc: 0.7530
Epoch 56/60
 - 1s - loss: 0.4852 - acc: 0.7518
Epoch 57/60
 - 1s - loss: 0.4834 - acc: 0.7515
Epoch 58/60
 - 1s - loss: 0.4802 - acc: 0.7588
Epoch 59/60
 - 1s - loss: 0.4785 - acc: 0.7589
Epoch 60/60
 - 2s - loss: 0.4763 - acc: 0.7577

In [14]:
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.8455 - acc: 0.6188
Normal Neural Network - Loss: 0.8454657235559827, Accuracy: 0.6188129186630249

In [15]:
encoded_predictions = model.predict_classes(X_test_scaled[:5])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\setho\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [16]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:5])}")

Predicted classes: [1 1 0 1 0]
Actual Labels: [0, 0, 0, 0, 1]

In [33]:
predictions = model.predict(X_test)
predictions

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [18]:
# Save the model
model.save("nfl_keras_DL")

In [19]:
# Load the model
from tensorflow.keras.models import load_model
model = load_model("nfl_keras_DL")

In [20]:
# Evaluate the model using the training data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.8455 - acc: 0.6188
Loss: 0.8454657235559827, Accuracy: 0.6188129186630249

In [42]:
# y_test

In [37]:
predictions.ravel()

array([0., 1., 0., ..., 0., 1., 0.], dtype=float32)

In [39]:
y_actu = pd.Series(y_test, name='Actual')
y_pred = pd.Series(predictions.ravel(), name='Predicted')
df_confusion = pd.crosstab(y_actu ,y_pred)
df_confusion

Predicted  0.0  1.0
Actual
0          792  405
1          786  409
2            4    1

In [43]:
# y_pred